99 rapla daten in gruppe automatisch einfügen -> dev
maxomnia/pm_project_rapla pull request #105
Opened 2022-07-15 18:27 UTC by sockel12

Sollte soweit funktionieren

2022-07-15 20:25 UTC, maxomnia requested changes
![image](https://user-images.githubusercontent.com/68776978/179305265-7033d00f-ed7c-4e50-bdb2-0f723ea725ad.png)
Hier kommt ein Fehler, wenn ich versuche die Gruppe TINF21B1 zu erstellen mit der URL `rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=freudenmann&file=TINF21B1`

2022-07-15 20:25 UTC, maxomnia commented on lib/handlers.ts
>          fs.opendir(`${dataDir}`, (err: NodeJS.ErrnoException | null, dir: fs.Dir) => {
Kannst du den Fehler den CodeQL in Zeile 123 anzeigt beheben?

2022-07-15 20:25 UTC, maxomnia commented on lib/xml_manager.ts
> -                return false;
Wieso das reformatting 😭

2022-07-16 20:59 UTC, maximiliani commented
Prinzipiell funktioniert der Code, leider hast du aber vergessen die Daten vom iCal in unser Format zu konvertieren. So können die Daten leider nicht benutzt werden...

2022-07-17 10:52 UTC, sockel12 commented
> ![image](https://user-images.githubusercontent.com/68776978/179305265-7033d00f-ed7c-4e50-bdb2-0f723ea725ad.png)
> Hier kommt ein Fehler, wenn ich versuche die Gruppe TINF21B1 zu erstellen mit der URL `rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=freudenmann&file=TINF21B1`


Also ich habe hier kein Problem, ich kann dann einfach die Gruppe nicht erstellen? Hast du das auf einem eigenen Account gemacht?

2022-07-17 12:04 UTC, maxomnia requested changes

2022-07-17 12:04 UTC, maxomnia commented on app.ts
> +    Handlers.updateRaplaEvents("freudenmann", "TINF21B1")
Wieso hast du das wieder hinzugefügt? Das sollte doch für alle Gruppen laufen, die eine gültige Rapla URL haben und nicht nur für unseren Kurs

2022-07-17 12:08 UTC, maximiliani commented on openapi.yaml
> +  /api/users/{uid}/groups:
Warum dafür einen extra Endpoint? Man kann doch einfach ein PUT für den User machen wo die Gruppen rausgelöscht sind...

2022-07-17 12:09 UTC, maxomnia commented on openapi.yaml
> +  /api/users/{uid}/groups:
Das ist von mir. Ich wollte Silas nur schnell eine Lösung geben. Ich würde das jetzt einfach so lassen. Das ist ja auch kein richtiger Endpoint, sondern nur eine Erweiterung wie man so schön sagt

2022-07-17 12:10 UTC, maxomnia reviewed
Sollte passen oder?

2022-07-17 12:14 UTC, maximiliani commented on routers/calendar_router.ts
> +        //request.user.editableGroup.uid == request.params.uid ||
Hier müsste man eigentlich eine Überprüfung machen, ob der User, der die Request macht, die Gruppe mit der UID als editableGroup eingetragen hat...

2022-07-17 12:15 UTC, sockel12 commented
Ich mache das jetzt mal mit den richtigen Daten

2022-07-17 12:18 UTC, maximiliani commented
Kannst du Zeile 120 in der utils.ts (function getNextUID) durch `return "U" + currUID` ersetzen. Sonst gibt das Probleme mit den UIDs. Ich dachte eigentlich, dass ich das schon gefixt hätte.

2022-07-17 12:21 UTC, maxomnia commented on routers/calendar_router.ts
> +        //request.user.editableGroup.uid == request.params.uid ||
@maximiliani Mach du das doch fix. Das ist ja meine Änderung vom dev

2022-07-17 12:37 UTC, sockel12 commented
Max einmal bitte überprüfen :D

2022-07-17 12:44 UTC, maxomnia requested changes
Das Laden und konvertieren funktioniert schonmal gut. Die ganzen Events müssten nur noch im events Verzeichnis unter dem Hash der Gruppe gespeichert werden

2022-07-17 12:46 UTC, sockel12 commented
> Das Laden und konvertieren funktioniert schonmal gut. Die ganzen Events müssten nur noch im events Verzeichnis unter dem Hash der Gruppe gespeichert werden

Tun sie doch? Du meinst doch in ../data/events/{Hash der Gruppe} oder nicht?

2022-07-17 12:49 UTC, maxomnia commented
> > Das Laden und konvertieren funktioniert schonmal gut. Die ganzen Events müssten nur noch im events Verzeichnis unter dem Hash der Gruppe gespeichert werden
> 
> Tun sie doch? Du meinst doch in ../data/events/{Hash der Gruppe} oder nicht?

Hast Recht. Habe ich übersehen

2022-07-17 12:49 UTC, maxomnia approved these changes

2022-07-17 12:52 UTC, merged